### PR TITLE
Add google authentication to app itself

### PR DESCRIPTION
**Pull request by ong-yinggao98**
Known issues:
~~Logging out from settings has a UI bug that overlays login page over the settings page temporarily~~

Good to have:
loading status hook and loading page for favourites and settings so users don't see a "you aren't logged in" page before it actually loads

### CODE REVIEW

**Comment by teo-jun-xiong** [comment]
Adding `routerLink="/" routerDirection="root"` fixes that overlay.

**Comment by ong-yinggao98** [comment]
> Adding `routerLink="/" routerDirection="root"` fixes that overlay.

I fixed it by using `history.replace('/')` instead of `history.push('/')`. But where would you put that line?

**Comment by teo-jun-xiong** [comment]
```
 <div className="sign-out" onClick={trackGoogleSignOutEvent}>
          <IonButton className="sign-out__button" shape="round" routerLink="/" routerDirection="root">
            Sign Out
          </IonButton>
</div>
```

We can replace `trackGoogleSignOutEvent` to include the signout function from `react-google-login`

**Comment by ong-yinggao98** [comment]
> In `IonicButton ... routerLink="/" routerDirection="root" />`

The buttons perform navigation in a callback when there is a successful logout so I think I'd rather not put it as a button prop in case it redirects when it doesn't actually log out.

Also right now the token is just stored locally but I don't know how to handle the case where it expires.

**Comment by teo-jun-xiong** [comment]
I think using `history.replace(...)` works, just that `routerLink` is how IonicReactRouter handles it. I think both are fine.

> the case where it expires

Does this help? https://stackoverflow.com/questions/51292406/jwt-check-if-token-expired

**Pull request merged**
